---
# tasks file for command zmcontrol restart

- shell: zmcontrol restart
  become: yes
  become_user: zimbra
  become_method: sudo
  become_flags: '-i'
  register: result
  tags: zmcontrol_restart

- debug:
    var: result.stdout
