---
# tasks file for command zmcontrol start

- shell: zmcontrol start
  become: yes
  become_user: zimbra
  become_method: sudo
  become_flags: '-i'
  register: result
  tags: zmcontrol_start

- debug:
    var: result.stdout
