---
# tasks file for command zmcontrol stop

- shell: zmcontrol stop
  become: yes
  become_user: zimbra
  become_method: sudo
  become_flags: '-i'
  register: result
  tags: zmcontrol_stop

- debug:
    var: result.stdout
