---
# tasks file for command zmcontrol -v

- shell: zmcontrol -v
  become: yes
  become_user: zimbra
  become_method: sudo
  become_flags: '-i'
  register: result
  tags: zmcontrol_version

- debug:
    var: result.stdout
